// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2015rfvgdfbefb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2015rfvgdfbefb));
        
        string IMigrationMetadata.Id
        {
            get { return "201506231235544_2015rfvgdfbefb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
