// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20150622942 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150622942));
        
        string IMigrationMetadata.Id
        {
            get { return "201506220642460_2015-06-22-9-42"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
