// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_comments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_comments));
        
        string IMigrationMetadata.Id
        {
            get { return "201506211550240_add_comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
