// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161901244 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161901244));
        
        string IMigrationMetadata.Id
        {
            get { return "201601182344418_2016-19-01-2-44"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
