// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _170120160139 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_170120160139));
        
        string IMigrationMetadata.Id
        {
            get { return "201601162240460_17-01-2016-01-39"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
