//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.RSSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="RSSServiceReference.RSStoHTMLSoap")]
    public interface RSStoHTMLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetHTML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHTML(string RSSURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetHTML", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHTMLAsync(string RSSURL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RSStoHTMLSoapChannel : HelloWorld.RSSServiceReference.RSStoHTMLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RSStoHTMLSoapClient : System.ServiceModel.ClientBase<HelloWorld.RSSServiceReference.RSStoHTMLSoap>, HelloWorld.RSSServiceReference.RSStoHTMLSoap {
        
        public RSStoHTMLSoapClient() {
        }
        
        public RSStoHTMLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RSStoHTMLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSStoHTMLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSStoHTMLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHTML(string RSSURL) {
            return base.Channel.GetHTML(RSSURL);
        }
        
        public System.Threading.Tasks.Task<string> GetHTMLAsync(string RSSURL) {
            return base.Channel.GetHTMLAsync(RSSURL);
        }
    }
}
